#:schema node_modules/wrangler/config-schema.json
# name = "test-monrepo12345678-1"
main = "worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

[vars]
API_HOST = "example.com"
API_ACCOUNT_ID = "example_user"

